# Service Config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ template "jenkins.namespace" . }}
spec:
  selector:
    app: {{ template "jenkins.label" . }}
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.servicePorts }}
  - name: {{ .name }}
    port: {{ .port  }}
    targetPort: {{ .targetPort }}
  {{- end }}
