apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ template "nexus.namespace" . }}
spec:
  storageClassName: {{ .Values.volume.storageClass | default "''" }}
  accessModes:
 {{ toYaml .Values.volume.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
  {{- if .Values.pvc.selector }}
  selector:
{{ toYaml .Values.pvc.selector | indent 4}}
{{- end }}
