apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.data.pvName }}
  labels:
    type: {{ .Values.volume.type }}
spec:
  storageClassName: {{ .Values.storageClassName | default "''" }}
  capacity:
    storage: {{ .Values.volume.data.dataSize }}
  accessModes:
  {{ toYaml .Values.accessModes | indent 2 }}
  claimRef:
    namespace: {{ template "gitlab.namespace" . }}
    name: {{ .Values.volume.data.pvcName }}
  {{- if eq .Values.volume.type "nfs" }}
  nfs:
    path: {{ .Values.nfs.dataPath }}
    server: {{ .Values.nfs.server }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.log.pvName }}
  labels:
    type: {{ .Values.volume.type }}
spec:
  storageClassName: {{ .Values.storageClassName | default "''" }}
  capacity:
    storage: {{ .Values.volume.log.dataSize }}
  accessModes:
  {{ toYaml .Values.accessModes | indent 2 }}
  claimRef:
    namespace: {{ template "gitlab.namespace" . }}
    name: {{ .Values.volume.log.pvcName }}
  {{- if eq .Values.volume.type "nfs" }}
  nfs:
    path: {{ .Values.nfs.logPath }}
    server: {{ .Values.nfs.server }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.config.pvName }}
  labels:
    type: {{ .Values.volume.type }}
spec:
  storageClassName: {{ .Values.storageClassName | default "''" }}
  capacity:
    storage: {{ .Values.volume.config.dataSize }}
  accessModes:
  {{ toYaml .Values.accessModes | indent 2 }}
  claimRef:
    namespace: {{ template "gitlab.namespace" . }}
    name: {{ .Values.volume.config.pvcName }}
  {{- if eq .Values.volume.type "nfs" }}
  nfs:
    path: {{ .Values.nfs.configPath }}
    server: {{ .Values.nfs.server }}
  {{- end }}
