apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.data.pvcName }}
  namespace: {{ template "gitlab.namespace" . }}
spec:
  storageClassName: {{ .Values.volume.storageClassName | default "''" }}
  accessModes:
  {{ toYaml .Values.accessModes | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.volume.data.dataSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.log.pvcName }}
  namespace: {{ template "gitlab.namespace" . }}
spec:
  storageClassName: {{ .Values.volume.storageClassName | default "''" }}
  accessModes:
  {{ toYaml .Values.accessModes | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.volume.log.dataSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.config.pvcName }}
  namespace: {{ template "gitlab.namespace" . }}
spec:
  storageClassName: {{ .Values.volume.storageClassName | default "''" }}
  accessModes:
  {{ toYaml .Values.accessModes | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.volume.config.dataSize }}
