apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.name" . }}
  namespace: {{ template "gitlab.namespace" . }}
spec:
  selector:
    app: {{ template "gitlab.name" . }}
  ports:
  {{- range .Values.servicePorts }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  type: {{ .Values.serviceType | default "clusterIp" }}
